<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto

namespace PhluxorSaga\Metadata\ProtoBuf;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9D\x02\x0A\x0Bevent.proto\x12\x08protobuf\" \x0A\x0ETransferFailed\x12\x0E\x0A\x06reason\x18\x01 \x01(\x09\"\x0F\x0A\x0DStatusUnknown\"\x11\x0A\x0FTransferStarted\"\x10\x0A\x0EAccountDebited\"\"\x0A\x10EscalateTransfer\x12\x0E\x0A\x06reason\x18\x01 \x01(\x09\"\x17\x0A\x15FailedAndInconsistent\"\x1B\x0A\x19FailedButConsistentResult\"\x11\x0A\x0FDebitRolledBackB7\xCA\x02\x14PhluxorSaga\\ProtoBuf\xE2\x02\x1DPhluxorSaga\\Metadata\\ProtoBufb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

